const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || '';

export const API_ENDPOINTS = {
    LOGIN: `/login`,
    REGISTER: `/register`,
    TICKETS: `/api/tickets`,
    SINGLE_TICKET: `/tickets`,
    STATUSES: `/api/status`,
    USERS: `/api/users`,
    PROJECTS: `/api/projects`,
    METRICS: `/api/metrics`,
    PROGRESS: `/api/progress-pulse`,
    ATTACHMENTS: `/upload_attachment`,
    MESSAGES: `/add_ticket_message`,
    TICKET_MESSAGES: `/get_ticket_messages`,
    TICKET_ATTACHMENTS: `/get_ticket_attachments`,
    DELETE_ATTACHMENT: `/delete_attachment`,
    PERMANENTLY_DELETE_TICKET: `/permanently_delete_ticket`,
    UPDATE_TICKET_STATUS: `/tickets`,
    CREATE_TICKET: `/create_ticket`,
    EDIT_TICKET: `/edit-ticket`,
    TEAM_PERFORMANCE: `/api/team-performance`,
    METRICS_CARDS: `/api/metricscards`,
    TASK_STATUS_DISTRIBUTION: `/api/task-status-distribution`,
    WORKLOAD_DISTRIBUTION: `/api/workload-distribution`,
    PRIORITY_DISTRIBUTION: `/api/priority-distribution`,
    STATUS_DISTRIBUTION: `/api/status-distribution`,
    TICKET_STATS: `/api/ticket-stats`,
    METRICS_OVERVIEW: `/api/metrics-overview`,
    TICKET_STATUS_DISTRIBUTION: `/api/ticket-status-distribution`,
    ADD_TAG_CONSTRAINT: `/api/add-tag-constraint`,
    ADD_STATUS: `/api/add_status`,
    GET_ALL_STATUSES: `/api/tickets/status`,
    GET_ALL_RESPONSES: `/api/responses`,
    SUBMIT_RESPONSES: `/api/responses`,
    GET_TICKET_RESPONSES: `/api/responses`
};
